return {
	tools = {
		"basedpyright",
		"ruff",
		"debugpy",
		"prettier",
		"typescript-language-server",
		"stylua",
		"lua-language-server",
		"shfmt",
		"shellcheck",
		"bash-language-server",
		"jq",
		"yamllint",
		"yaml-language-server",
	},
	parsers = {
		"javascript",
		"typescript",
		"python",
		"vim",
		"vimdoc",
		"json",
		"html",
		"bash",
		"css",
		"csv",
		"r",
		"lua",
		"markdown",
		"markdown_inline",
		"latex",
		"yaml",
	},
	host_packages = { "pynvim", "jupyter_client", "nbformat" },
	notebook_packages = { "ipykernel", "pandas", "matplotlib" },
	prerequisites = { "git", "uv", "node", "npm", "yarn", "cc", "tree-sitter", "curl", "tar" },
}
