describe("notebook cell borders", function()
	local buf, borders
	before_each(function()
		buf = vim.api.nvim_create_buf(false, true)
		vim.api.nvim_buf_set_name(buf, vim.fn.tempname() .. ".ipynb")
		borders = require("config.notebook_borders")
	end)
	after_each(function()
		vim.api.nvim_buf_delete(buf, { force = true })
	end)
	it("encloses code without adding source or virtual rows", function()
		local lines = { "# Heading", "```python", "print('hello')", "```", "prose" }
		vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
		borders.refresh(buf)
		local marks = vim.api.nvim_buf_get_extmarks(buf, borders.ns, 0, -1, { details = true })
		assert.equals(4, #marks)
		assert.same(lines, vim.api.nvim_buf_get_lines(buf, 0, -1, false))
		for _, mark in ipairs(marks) do
			assert.is_true(mark[2] >= 1 and mark[2] <= 3)
			assert.is_nil(mark[4].virt_lines)
		end
	end)
	it("removes borders when a cell is deleted", function()
		vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "```python", "x = 1", "```" })
		borders.refresh(buf)
		vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "prose" })
		borders.refresh(buf)
		assert.same({}, vim.api.nvim_buf_get_extmarks(buf, borders.ns, 0, -1, {}))
	end)
	it("fills the window excluding its gutter and follows resizing", function()
		vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "```python", "x = 1", "```" })
		local win = vim.api.nvim_open_win(buf, true, { relative = "editor", row = 0, col = 0, width = 72, height = 8 })
		vim.wo[win].number = true
		for _, size in ipairs({ 72, 45 }) do
			vim.api.nvim_win_set_width(win, size)
			borders.refresh(buf)
			local marks = vim.api.nvim_buf_get_extmarks(buf, borders.ns, 0, -1, { details = true })
			local width = size - vim.fn.getwininfo(win)[1].textoff
			assert.equals(width, vim.fn.strdisplaywidth(marks[1][4].virt_text[1][1]))
			assert.equals(width - 1, marks[3][4].virt_text_win_col)
		end
		vim.api.nvim_win_close(win, true)
	end)
	it("ignores ordinary markdown buffers", function()
		vim.api.nvim_buf_set_name(buf, vim.fn.tempname() .. ".md")
		vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "```python", "x = 1", "```" })
		borders.refresh(buf)
		assert.same({}, vim.api.nvim_buf_get_extmarks(buf, borders.ns, 0, -1, {}))
	end)
end)
